name: esc-rotator-lambda
runtime: nodejs
description: This pulumi program will deploy the rotation lambda into your VPC and will set up a role to allow ESC to invoke it.
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
    rdsDbIdentifier:
      description: The database identifier of the RDS cluster the lambda will rotate credentials in.
    rotatedSecretsEnvironmentName:
      description: Name of the environment that will rotate the DB credentials. Format of the name needs to be `myProject/myEnvironment`.
    managingCredsEnvironmentName:
      description: >-
        (Optional) Name of the environment that will contain the privileged managing user credentials used to rotate the user DB credentials.
        Format of the name needs to be `myProject/myEnvironment`. You can skip specifying this one, and it will be derived from `environmentName`.
    backendUrl:
      default: https://api.pulumi.com
      description: >-
        (Optional) The Pulumi Cloud URL. Change this URL ONLY if you are self-hosting Pulumi Cloud.
