name: esc-rotator-lambda
runtime: nodejs
description: This pulumi program will deploy the rotation lambda into your VPC and will set up a role to allow ESC to invoke it.
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
    rdsId:
      description: The ID of the RDS cluster the lambda will proxy access to.
    environmentName:
      description: Name of the rotator environment to be created. Format needs to be `myProject/myEnvironment`.
    managingCredsEnvironmentName:
      description: >-
        Name of the managing credentials environment to be created. Format needs to be `myProject/myEnvironment`.
        You can skip specifying this one, and it will be derived from `environmentName`.
    backendUrl:
      default: https://api.pulumi.com
      description: >-
        The Pulumi backend URL. Unless you use Pulumi self-hosted, leave this as default.
