name: esc-rotator-lambda
runtime: nodejs
description: This pulumi program will deploy the rotation lambda into your VPC and will set up a role to allow ESC to invoke it.
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2
    rdsId:
      description: The ID of the RDS cluster the lambda will proxy access to.
    environmentName:
      description: Name of the rotator environment to be created. Format needs to be `myProject/myEnvironment`.
    managingCredsEnvironmentName:
      description: >-
        Name of the managing credentials environment to be created. Format needs to be `myProject/myEnvironment`.
        You can skip specifying this one, and it will be derived from `environmentName`.
    allowlistedEnvironment:
      description: >-
        The ESC environment(s) that are allowed to use the rotation lambda.
        Pulumi will set fully qualified ESC environment name as an IAM external id when assuming
        the role to invoke the lambda like `{pulumi organization}/{esc project}/{esc env name}`.
        You can use `*` as wildcard to match more than one environment. For example, `myOrg/myProject/*` will match all environments in the `myProject` project. 
        See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html
        If you leave this config empty, allowlist will be scoped down to your organization only, like so `myOrg/*`.
